### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by jasonlll88** [mhehm/mod_currentdatetime#12]
Hello, how can i use the CSS box, to put in the center the date and time.

thx

**Comment by gptforjoomla** [comment]
you can add css to module's elements classes. check classes by firebug or view source. example for your need:
.datetime {text-align: center}

**Comment by jasonlll88** [comment]
Thx for your quick answer.
It's possible to change the idiom of the day, or just print the numbers of the date?

**Comment by gptforjoomla** [comment]
Hi, you can select what you want to show in module parameters

**Comment by jasonlll88** [comment]
thx
