### ISSUE TITLE
menu proble with jQuery

### ISSUE THREAD

**Issue by gitHub711** [mhehm/mod_currentdatetime#7]
Hi Mohammad
the module is excellent
but unfortunately the menus are locked when we activate jQuery in analog clock settings
if it has a solution I would appreciate to tell me
(mfakhri59@yahoo.com)

**Comment by mhehm** [comment]
Hi,
This is usually because of JavaScript conflict.
If your template load jquery, disable jquery in module.

**Comment by gitHub711** [comment]
on disabling jquery in module, i miss the analog clock!anyway thank you very much 

     On Thursday, 15 January 2015, 11:24, Mohammad Hasani Eghtedar <notifications@github.com> wrote:
   

 Hi,
This is usually because of JavaScript conflict.
If your template load jquery, disable jquery in module.—

**Comment by gitHub711** [comment]
با سلام و احتراممن میخواستم یک تغییر کوچک در یک کامپوننت جوملا انجام بدهم اگر به من کمک کنید یا سفارش قبول کنید بسیار ممنون می‌شومکار هم به این صورت است که برای محدود کردن حق دسترسی یوزر میخواهم یک item selector که لیستی از مجموعه آیتم‌ها را نشان میدهد براساس یوز موردنظر فقط یک زیرمجموعه از آیتم ها را نشان بدهد (مثلا یوز شماره یک فقط آیتم‌های شماره یک و دو را ببیند و...)در صورتی که تمایل داشتید بفرمایید تا من اطلاعات بیشتری برایتان ارسال کنمبا تشکر...$arr = $db->loadObjectList(  );.. echo JHtml::_('select.options', $arr, 'value', 'text', $this->state->get('filter.item_id'));
 

     On Thursday, 15 January 2015, 14:32, mfakhri <mfakhri59@yahoo.com> wrote:
   

 on disabling jquery in module, i miss the analog clock!anyway thank you very much 

     On Thursday, 15 January 2015, 11:24, Mohammad Hasani Eghtedar <notifications@github.com> wrote:
   

 Hi,
This is usually because of JavaScript conflict.
If your template load jquery, disable jquery in module.—

**Comment by mhehm** [comment]
Think your problem fixed
