### ISSUE TITLE
Translation for gregorian date

### ISSUE THREAD

**Issue by Moostachio** [mhehm/mod_currentdatetime#9]
Hello,
First, thank you for this awesome module.

I have a little question about the translation.
I used to put the translation for the gregorian date, but I only have the month in my mother tongue (French), the day displays in english.
I tried to change the language path to translate days, but it still doesn't work.

What can I do to see the whole gregorian date in french ? :) 

Thank you.

**Comment by mhehm** [comment]
Hello, can you send me your translation files to i check it?
sent to my email: m.h.eghtedar@gmail.com

**Comment by Moostachio** [comment]
So I just have to modify my xml file in the module path ?

**Comment by mhehm** [comment]
no. uninstall module full and install it again
